! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Monitor.f90
! Time                 : Sat Jan 20 21:19:33 2018
! Working directory    : /home/zhuangjw/KPP/my_tests/GEOSChem
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'CH2I2          ','CH2ICl         ','CH2IBr         ', &
     'MONX           ','AERI           ','CO2            ', &
     'INDIOL         ','ISALA          ','ISALC          ', &
     'ISN1OA         ','ISN1OG         ','LBRO2H         ', &
     'LBRO2N         ','LISOPOH        ','LISOPNO3       ', &
     'LTRO2H         ','LTRO2N         ','LVOCOA         ', &
     'LVOC           ','LXRO2H         ','LXRO2N         ', &
     'MSA            ','PYAC           ','SO4H1          ', &
     'SO4H2          ','SOAGX          ','SOAIE          ', &
     'SOAME          ','IMAE           ','SOAMG          ', &
     'I2O4           ','CH3CCl3        ','DHDN           ', &
     'DHDC           ','I2O2           ','MONITA         ', &
     'BENZ           ','CH3I           ','H1301          ', &
     'H2402          ','I2O3           ','PMNN           ', &
     'PPN            ','TOLU           ','BrNO2          ', &
     'CCl4           ','CFC11          ','CFC12          ', &
     'CFC113         ','CFC114         ','CFC115         ', &
     'H1211          ','IBr            ','IEPOXD         ', &
     'INO            ','N2O            ','TRO2           ', &
     'BRO2           ','IEPOXA         ','IEPOXB         ', &
     'IONITA         ','N              ','OCS            ', &
     'XRO2           ','HI             ','MAP            ', &
     'CHCl3          ','ICl            ','IMAO3          ', &
     'CHBr3          ','MPN            ','Cl2O2          ', &
     'CH2Br2         ','CH2Cl2         ','HCFC141b       ', &
     'HCFC142b       ','HCFC22         ','ETP            ', &
     'DMS            ','IONO           ','OIO            ', &
     'RA3P           ','RB3P           ','XYLE           ', &
     'ClNO2          ','HCFC123        ','CH3Cl          ', &
     'CH3Br          ','HNO4           ','ClOO           ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_1 = (/ &
     'OClO           ','HNO2           ','PAN            ', &
     'RP             ','PP             ','PRPN           ', &
     'SO4            ','ALK4           ','PIP            ', &
     'R4P            ','HPALD          ','BrCl           ', &
     'N2O5           ','DHPCARP        ','C3H8           ', &
     'Br2            ','HC187          ','IAP            ', &
     'VRP            ','ATOOH          ','HOI            ', &
     'HPC52O2        ','MOBA           ','DHMOB          ', &
     'HONIT          ','RIPB           ','ISNP           ', &
     'MP             ','BrSALA         ','BrSALC         ', &
     'MAOP           ','MRP            ','EOH            ', &
     'RIPA           ','RIPD           ','ETHLN          ', &
     'ISNOHOO        ','C2H6           ','MTPA           ', &
     'NPMN           ','IONO2          ','MOBAOO         ', &
     'DIBOO          ','ISNOOB         ','LIMO           ', &
     'IPMN           ','INPN           ','MACRNO2        ', &
     'H              ','BrNO3          ','ROH            ', &
     'MONITS         ','I2             ','Cl2            ', &
     'ISOPNB         ','CH4            ','MVKOO          ', &
     'CH3CHOO        ','GAOO           ','MVKN           ', &
     'IEPOXOO        ','GLYX           ','MGLYOO         ', &
     'MGLOO          ','PRN1           ','MONITU         ', &
     'A3O2           ','CH2OO          ','PROPNN         ', &
     'MAN2           ','ISNOOA         ','PO2            ', &
     'B3O2           ','ISOPNDO2       ','MACROO         ', &
     'R4N1           ','MAOPO2         ','MACRN          ', &
     'H2O2           ','ISOP           ','ATO2           ', &
     'HCOOH          ','I              ','RCO3           ', &
     'IO             ','OLNN           ','OLND           ', &
     'LIMO2          ','KO2            ','HOBr           ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(53) :: SPC_NAMES_2 = (/ &
     'ISOPNBO2       ','PIO2           ','HC5OO          ', &
     'HNO3           ','ISOPND         ','ACTA           ', &
     'VRO2           ','HOCl           ','ISN1           ', &
     'GLYC           ','NMAO3          ','ClNO3          ', &
     'MGLY           ','ACET           ','HC5            ', &
     'RIO2           ','ETO2           ','INO2           ', &
     'R4O2           ','R4N2           ','HAC            ', &
     'MRO2           ','BrO            ','PRPE           ', &
     'RCHO           ','MEK            ','CH2O           ', &
     'MACR           ','ALD2           ','MVK            ', &
     'MCO3           ','SO2            ','MO2            ', &
     'CO             ','Cl             ','OH             ', &
     'NO3            ','NO             ','HBr            ', &
     'HO2            ','ClO            ','Br             ', &
     'H2O            ','O              ','NO2            ', &
     'HCl            ','O3             ','O1D            ', &
     'H2             ','MOH            ','N2             ', &
     'O2             ','RCOOH          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(233) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1, SPC_NAMES_2 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '       NO + O3 --> NO2 + O2                                                                         ', &
     '       OH + O3 --> HO2 + O2                                                                         ', &
     '      HO2 + O3 --> OH + 2 O2                                                                        ', &
     '      NO2 + O3 --> NO3 + O2                                                                         ', &
     '      MO2 + O3 --> CH2O + HO2 + O2                                                                  ', &
     '          2 OH --> H2O + O                                                                          ', &
     '          2 OH --> H2O2                                                                             ', &
     '      OH + HO2 --> H2O + O2                                                                         ', &
     '     H2O2 + OH --> HO2 + H2O                                                                        ', &
     '      NO + HO2 --> OH + NO2                                                                         ', &
     '         2 HO2 --> H2O2 + O2                                                                        ', &
     '       CO + OH --> CO2 + HO2                                                                        ', &
     '      CH4 + OH --> MO2 + H2O                                                                        ', &
     '      MO2 + NO --> CH2O + HO2 + NO2                                                                 ', &
     '     MO2 + HO2 --> MP + O2                                                                          ', &
     '         2 MO2 --> CH2O + MOH + O2                                                                  ', &
     '         2 MO2 --> 2 CH2O + 2 HO2                                                                   ', &
     '       MP + OH --> MO2 + H2O                                                                        ', &
     '       MP + OH --> CH2O + OH + H2O                                                                  ', &
     '    ATOOH + OH --> ATO2 + H2O                                                                       ', &
     '    ATOOH + OH --> MGLY + OH + H2O                                                                  ', &
     '     CH2O + OH --> CO + HO2 + H2O                                                                   ', &
     '      OH + NO2 --> HNO3                                                                             ', &
     '     HNO3 + OH --> NO3 + H2O                                                                        ', &
     '       OH + NO --> HNO2                                                                             ', &
     '     HNO2 + OH --> H2O + NO2                                                                        ', &
     '     HO2 + NO2 --> HNO4                                                                             ', &
     '          HNO4 --> HO2 + NO2                                                                        ', &
     '     HNO4 + OH --> H2O + NO2 + O2                                                                   ', &
     '     NO3 + HO2 --> OH + NO2 + O2                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '      NO3 + NO --> 2 NO2                                                                            ', &
     '      OH + NO3 --> HO2 + NO2                                                                        ', &
     '     NO3 + NO2 --> N2O5                                                                             ', &
     '          N2O5 --> NO3 + NO2                                                                        ', &
     '    HCOOH + OH --> CO2 + HO2 + H2O                                                                  ', &
     '      OH + MOH --> CH2O + HO2                                                                       ', &
     '     NO3 + NO2 --> NO + NO2 + O2                                                                    ', &
     '    CH2O + NO3 --> HNO3 + CO + HO2                                                                  ', &
     '     ALD2 + OH --> 0.05 CH2O + 0.95 MCO3 + 0.05 CO + 0.05 HO2 + H2O                                 ', &
     '    ALD2 + NO3 --> HNO3 + MCO3                                                                      ', &
     '    MCO3 + NO2 --> PAN                                                                              ', &
     '           PAN --> MCO3 + NO2                                                                       ', &
     '     MCO3 + NO --> CO2 + MO2 + NO2                                                                  ', &
     '     C2H6 + OH --> ETO2 + H2O                                                                       ', &
     '     ETO2 + NO --> ALD2 + HO2 + NO2                                                                 ', &
     '     C3H8 + OH --> B3O2                                                                             ', &
     '     C3H8 + OH --> A3O2                                                                             ', &
     '     A3O2 + NO --> RCHO + HO2 + NO2                                                                 ', &
     '      PO2 + NO --> CH2O + ALD2 + HO2 + NO2                                                          ', &
     '     ALK4 + OH --> R4O2                                                                             ', &
     '     R4O2 + NO --> 0.05 A3O2 + 0.18 B3O2 + 0.32 ACET + 0.32 ETO2 + 0.14 RCHO ... etc.               ', &
     '     R4O2 + NO --> R4N2                                                                             ', &
     '     R4N1 + NO --> 0.57 RCHO + 0.57 CH2O + 0.86 ALD2 + 2 NO2                                        ', &
     '     ATO2 + NO --> CH2O + MCO3 + NO2                                                                ', &
     '      KO2 + NO --> 0.07 R4N2 + 0.93 ALD2 + 0.93 MCO3 + 0.93 NO2                                     ', &
     '     RIO2 + NO --> 0.03 DIBOO + 0.081 ISOPNB + 0.009 ISOPND + 0.058 HC5 ... etc.                    ', &
     '          RIO2 --> 0.5 HPALD + 0.5 DHPCARP                                                          ', &
     '     VRO2 + NO --> 0.12 MVKN + 0.53 GLYC + 0.35 MGLY + 0.35 CH2O + 0.53 MCO3 ... etc.               ', &
     '     MRO2 + NO --> 0.15 MACRN + 0.122 MGLY + 0.728 HAC + 0.122 CH2O + 0.728 CO ... etc.             ', &
     '          MRO2 --> HAC + CO + OH                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '     MAN2 + NO --> 0.5 PROPNN + 0.5 MGLY + 0.5 CH2O + 0.5 CO + 0.5 OH + 1.5 NO2 ... etc.            ', &
     '     B3O2 + NO --> ACET + HO2 + NO2                                                                 ', &
     '     INO2 + NO --> 0.7 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR + 0.035 MVK ... etc.                ', &
     '    INO2 + NO3 --> 0.7 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR + 0.035 MVK ... etc.                ', &
     '    ISN1 + NO3 --> 0.4 ISNOOB + 0.6 ISNOOA + 0.6 HNO3                                               ', &
     '  ISNOOA + NO3 --> 0.04 ISN1OG + 0.96 PROPNN + CO + HO2 + NO2                                       ', &
     '   ISNOOA + NO --> 0.04 ISN1OG + 0.96 PROPNN + CO + HO2 + NO2                                       ', &
     '  ISNOOA + NO2 --> 0.04 ISN1OG + 0.96 IPMN                                                          ', &
     '  ISNOOA + HO2 --> 0.04 ISN1OG + 0.75 RP + 0.96 NO2 + 0.25 O3 + 0.25 RCOOH ... etc.                 ', &
     '  ISNOOB + NO3 --> 0.04 ISN1OG + GLYX + 0.94 PROPNN + 2 NO2                                         ', &
     '   ISNOOB + NO --> 0.04 ISN1OG + 0.94 GLYX + 0.9 PROPNN + 1.88 NO2                                  ', &
     '  ISNOOB + HO2 --> 0.04 ISN1OG + 0.96 INPN                                                          ', &
     '  ISNOOB + MO2 --> 0.04 ISN1OG + 0.7 GLYX + 0.66 PROPNN + 0.75 CH2O + 0.5 HO2 ... etc.              ', &
     '     ISN1 + O3 --> 0.7 GLYX + 0.3 PROPNN + 0.75 CH2O + 0.5 HO2 + 0.7 NO2 ... etc.                   ', &
     '     ISN1 + OH --> 0.655 ISNOHOO + 0.345 ISNOOA                                                     ', &
     '  ISNOHOO + NO --> 0.04 ISN1OG + 0.919 GLYX + 0.894 PROPNN + 0.934 HO2 ... etc.                     ', &
     ' ISNOHOO + HO2 --> 0.04 ISN1OG + 0.96 INPN                                                          ', &
     ' ISNOHOO + MO2 --> 0.04 ISN1OG + 0.7 GLYX + 0.66 PROPNN + 0.75 CH2O + 1.2 HO2 ... etc.              ', &
     '        2 INO2 --> 0.5 ISOPND + 1.2 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR ... etc.               ', &
     '     PRN1 + NO --> CH2O + ALD2 + 2 NO2                                                              ', &
     '    ALK4 + NO3 --> HNO3 + R4O2                                                                      ', &
     '     R4N2 + OH --> R4N1 + H2O                                                                       ', &
     '     ACTA + OH --> CO2 + MO2 + H2O                                                                  ', &
     '     RCHO + OH --> RCO3 + H2O                                                                       ', &
     '    RCO3 + NO2 --> PPN                                                                              ', &
     '           PPN --> RCO3 + NO2                                                                       ', &
     '   IMAO3 + NO2 --> IPMN                                                                             ', &
     '   NMAO3 + NO2 --> NPMN                                                                             ', &
     '          IPMN --> IMAO3 + NO2                                                                      ', &
     '          NPMN --> NMAO3 + NO2                                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '     RCO3 + NO --> ETO2 + NO2                                                                       ', &
     '    NMAO3 + NO --> CO2 + 0.5 CH2O + 0.5 MCO3 + 0.5 MO2 + 0.5 CO + NO2                               ', &
     '    RCHO + NO3 --> RCO3 + HNO3                                                                      ', &
     '     ACET + OH --> ATO2 + H2O                                                                       ', &
     '    A3O2 + MO2 --> 0.25 ROH + 0.75 RCHO + 0.75 CH2O + HO2 + 0.25 MOH                                ', &
     '     PO2 + MO2 --> 0.25 ROH + 0.16 HAC + 0.09 RCHO + 1.25 CH2O + 0.5 ALD2 ... etc.                  ', &
     '    R4O2 + HO2 --> R4P                                                                              ', &
     '    R4N1 + HO2 --> R4N2                                                                             ', &
     '    ATO2 + HO2 --> 0.85 ATOOH + 0.15 CH2O + 0.15 MCO3 + 0.15 OH                                     ', &
     '     KO2 + HO2 --> 0.85 ATOOH + 0.15 ALD2 + 0.15 MCO3 + 0.15 OH                                     ', &
     '    RIO2 + HO2 --> 0.272 RIPB + 0.628 RIPA + 0.037 RIPD + 0.063 CH2O + 0.025 MACR ... etc.          ', &
     '    VRO2 + HO2 --> 0.1 VRP + 0.578 GLYC + 0.102 MGLY + 0.033 RCHO + 0.187 MEK ... etc.              ', &
     '    MRO2 + HO2 --> MRP                                                                              ', &
     '    MAN2 + HO2 --> 0.85 MAOP + 0.075 PROPNN + 0.075 MGLY + 0.075 CH2O + 0.075 CO ... etc.           ', &
     '    B3O2 + HO2 --> RB3P                                                                             ', &
     '    INO2 + HO2 --> INPN                                                                             ', &
     '    PRN1 + HO2 --> PRPN                                                                             ', &
     '      MEK + OH --> KO2 + H2O                                                                        ', &
     '    ETO2 + MO2 --> 0.25 EOH + 0.75 CH2O + 0.75 ALD2 + HO2 + 0.25 MOH                                ', &
     '     MEK + NO3 --> KO2 + HNO3                                                                       ', &
     '    R4O2 + MO2 --> 0.25 ROH + 0.03 A3O2 + 0.09 B3O2 + 0.16 ACET + 0.16 ETO2 ... etc.                ', &
     '    R4N1 + MO2 --> 0.25 ROH + 0.15 R4O2 + 0.54 RCHO + 0.95 CH2O + 0.38 ALD2 ... etc.                ', &
     '    ATO2 + MO2 --> 0.5 MGLY + 0.2 HAC + 0.5 CH2O + 0.3 MCO3 + 0.3 HO2 + 0.5 MOH ... etc.            ', &
     '     KO2 + MO2 --> 0.25 ROH + 0.25 MEK + 0.75 CH2O + 0.5 ALD2 + 0.5 MCO3 ... etc.                   ', &
     '    RIO2 + MO2 --> 0.24 ROH + 0.3 HC5 + 1.22 CH2O + 0.18 MACR + 0.28 MVK ... etc.                   ', &
     '        2 RIO2 --> 0.09 DIBOO + 1.11 HC5 + 0.75 CH2O + 0.29 MACR + 0.45 MVK ... etc.                ', &
     '   HC5OO + MO2 --> 0.25 ROH + 0.13 GLYC + 0.29 MGLY + 0.18 HAC + 0.25 MEK ... etc.                  ', &
     '    VRO2 + MO2 --> 0.25 ROH + 0.36 GLYC + 0.14 MGLY + 0.25 MEK + 0.89 CH2O ... etc.                 ', &
     '    MRO2 + MO2 --> 0.15 ROH + 0.255 MGLY + 0.595 HAC + 1.255 CH2O + 0.595 CO ... etc.               ', &
     '    MAN2 + MO2 --> 0.375 PROPNN + 0.375 MGLY + 0.25 R4N2 + 0.625 CH2O + 0.375 CO ... etc.           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '    B3O2 + MO2 --> 0.25 ROH + 0.75 ACET + 0.75 CH2O + HO2 + 0.25 MOH                                ', &
     '    INO2 + MO2 --> 0.25 ISOPND + 0.6 ISN1 + 0.115 HC5 + 0.785 CH2O + 0.018 MACR ... etc.            ', &
     '    PRN1 + MO2 --> 0.25 ROH + 0.25 RCHO + 1.25 CH2O + 0.5 ALD2 + 0.5 HO2 ... etc.                   ', &
     '      EOH + OH --> ALD2 + HO2                                                                       ', &
     '      ROH + OH --> RCHO + HO2                                                                       ', &
     '        2 ETO2 --> 2 ALD2 + 2 HO2                                                                   ', &
     '        2 ETO2 --> EOH + ALD2                                                                       ', &
     '    ETO2 + HO2 --> ETP                                                                              ', &
     '    A3O2 + HO2 --> RA3P                                                                             ', &
     '     PO2 + HO2 --> PP                                                                               ', &
     '    MCO3 + HO2 --> 0.41 MAP + 0.15 ACTA + 0.44 MO2 + 0.44 OH + 0.15 O3 ... etc.                     ', &
     '    RCO3 + HO2 --> 0.41 RP + 0.44 ETO2 + 0.44 OH + 0.15 O3 + 0.15 RCOOH ... etc.                    ', &
     '   NMAO3 + HO2 --> 0.41 MAOP + 0.59 CH2O + 0.39 MO2 + 0.39 CO + 0.44 OH ... etc.                    ', &
     '     PRPE + OH --> PO2                                                                              ', &
     '     PRPE + O3 --> 0.1 CH4 + 0.12 CH3CHOO + 0.12 CH2OO + 0.5 CH2O + 0.5 ALD2 ... etc.               ', &
     '     NPMN + OH --> HAC + CO + NO2                                                                   ', &
     '     IPMN + OH --> 0.781 IMAE + 0.19 PAN + 0.03 HAC + 0.19 CH2O + 0.03 CO ... etc.                  ', &
     '     NPMN + O3 --> CH2O + MCO3 + NO3                                                                ', &
     '     IMAE + OH --> OH                                                                               ', &
     '     GLYC + OH --> 0.361 CO2 + 0.134 GLYX + 0.134 HCOOH + 0.732 CH2O + 0.505 CO ... etc.            ', &
     '     GLYC + OH --> HCOOH + CO + OH                                                                  ', &
     '    PRPE + NO3 --> PRN1                                                                             ', &
     '     GLYX + OH --> 2 CO + HO2                                                                       ', &
     '     MGLY + OH --> MCO3 + CO                                                                        ', &
     '    GLYX + NO3 --> HNO3 + 2 CO + HO2                                                                ', &
     '    MGLY + NO3 --> HNO3 + MCO3 + CO                                                                 ', &
     '     ISOP + OH --> LISOPOH + RIO2                                                                   ', &
     '      MVK + OH --> VRO2                                                                             ', &
     '     MACR + OH --> 0.53 IMAO3 + 0.47 MRO2                                                           ', &
     '      HAC + OH --> MGLY + HO2                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '      HAC + OH --> 0.5 CO2 + 0.5 HCOOH + 0.5 ACTA + 0.5 MO2 + 0.5 CO + OH ... etc.                  ', &
     '   A3O2 + MCO3 --> RCHO + MO2 + HO2                                                                 ', &
     '    PO2 + MCO3 --> CH2O + ALD2 + MO2 + HO2                                                          ', &
     '   A3O2 + MCO3 --> ACTA + RCHO                                                                      ', &
     '    PO2 + MCO3 --> ACTA + 0.65 HAC + 0.35 RCHO                                                      ', &
     '     ISOP + O3 --> 0.044 MVKOO + 0.11 CH2OO + 0.044 MACROO + 0.054 VRO2 ... etc.                    ', &
     '      MVK + O3 --> 0.12 MGLOO + 0.12 CH2OO + 0.5 MGLY + 0.6 CH2O + 0.1 ALD2 ... etc.                ', &
     '     MACR + O3 --> 0.022 MGLYOO + 0.326 CH2OO + 0.88 MGLY + 0.12 CH2O + 0.098 MCO3 ... etc.         ', &
     '    ISOP + NO3 --> LISOPNO3 + INO2                                                                  ', &
     '    MACR + NO3 --> MAN2                                                                             ', &
     '    MACR + NO3 --> 0.5 IMAO3 + 0.5 MAOP + 0.5 HNO3 + 0.5 MRO2 + 0.5 CO ... etc.                     ', &
     '    RCO3 + MO2 --> ETO2 + CH2O + HO2                                                                ', &
     '   NMAO3 + MO2 --> 2 CH2O + MCO3 + HO2                                                              ', &
     '    RCO3 + MO2 --> CH2O + RCOOH                                                                     ', &
     '   NMAO3 + MO2 --> CH2O + RCOOH                                                                     ', &
     '     INPN + OH --> MEK + OH + NO2                                                                   ', &
     '     INPN + OH --> 0.36 INO2 + 0.64 R4N2 + 0.64 OH                                                  ', &
     '     PRPN + OH --> 0.209 PRN1 + 0.791 PROPNN + 0.791 OH                                             ', &
     '      ETP + OH --> 0.36 ETO2 + 0.64 ALD2 + 0.64 OH                                                  ', &
     '     RA3P + OH --> 0.36 A3O2 + 0.64 RCHO + 0.64 OH                                                  ', &
     '     RB3P + OH --> 0.209 B3O2 + 0.791 ACET + 0.791 OH                                               ', &
     '      R4P + OH --> 0.209 R4O2 + 0.791 RCHO + 0.791 OH                                               ', &
     '       RP + OH --> RCO3                                                                             ', &
     '       PP + OH --> 0.209 PO2 + 0.791 HAC + 0.791 OH                                                 ', &
     '     RIPA + OH --> 0.005 LVOC + 0.245 HC5 + 0.75 RIO2 + 0.125 OH + 0.125 H2O ... etc.               ', &
     '     RIPB + OH --> 0.005 LVOC + 0.515 HC5 + 0.48 RIO2 + 0.26 OH + 0.26 H2O ... etc.                 ', &
     '     RIPD + OH --> 0.005 LVOC + 0.745 HC5 + 0.25 RIO2 + 0.375 OH + 0.375 H2O ... etc.               ', &
     '     RIPA + OH --> 0.005 LVOC + 0.578 IEPOXA + 0.272 IEPOXB + 0.145 HC5OO ... etc.                  ', &
     '     RIPB + OH --> 0.68 IEPOXA + 0.32 IEPOXB + OH                                                   ', &
     '     RIPD + OH --> 0.005 LVOC + 0.5 IEPOXD + 0.495 HC5OO + 0.5 OH                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '     LVOC + OH --> OH                                                                               ', &
     '   IEPOXA + OH --> IEPOXOO                                                                          ', &
     '   IEPOXB + OH --> IEPOXOO                                                                          ', &
     '   IEPOXD + OH --> IEPOXOO                                                                          ', &
     ' IEPOXOO + HO2 --> 1.172 CO2 + 0.44 HC187 + 0.085 GLYX + 0.278 HCOOH + 0.025 GLYC ... etc.          ', &
     '  IEPOXOO + NO --> 0.858 CO2 + 0.473 HC187 + 0.088 GLYX + 0.142 HCOOH + 0.088 GLYC ... etc.         ', &
     '      IAP + OH --> 0.654 DHMOB + 0.346 HC5OO + 0.654 OH                                             ', &
     '      VRP + OH --> 0.209 VRO2 + 0.791 MEK + 0.791 OH                                                ', &
     '      MRP + OH --> MRO2                                                                             ', &
     '      MRP + OH --> CO2 + HAC + OH                                                                   ', &
     '     MAOP + OH --> NMAO3                                                                            ', &
     '     MAOP + OH --> MAOPO2                                                                           ', &
     ' MAOPO2 + MCO3 --> 2 CO2 + HAC + MO2 + OH                                                           ', &
     ' MAOPO2 + MCO3 --> ACTA + MEK                                                                       ', &
     '  MAOPO2 + MO2 --> 0.7 CO2 + 0.3 ROH + 0.7 HAC + CH2O + 0.7 OH + 0.7 HO2 ... etc.                   ', &
     '      2 MAOPO2 --> 2 CO2 + 2 HAC + 2 OH                                                             ', &
     '  MAOPO2 + HO2 --> CO2 + HAC + 2 OH                                                                 ', &
     '   MAOPO2 + NO --> CO2 + HAC + OH + NO2                                                             ', &
     '   MAOPO2 + NO --> HNO3                                                                             ', &
     '      MAP + OH --> MCO3                                                                             ', &
     '    C2H6 + NO3 --> HNO3 + ETO2                                                                      ', &
     '      HC5 + O3 --> 0.055 GAOO + 0.055 MGLYOO + 0.5 GLYC + 0.5 MGLY + 0.445 CH2O ... etc.            ', &
     '        2 MCO3 --> 2 MO2                                                                            ', &
     '    MCO3 + MO2 --> CH2O + MO2 + HO2                                                                 ', &
     '    MCO3 + MO2 --> ACTA + CH2O                                                                      ', &
     '   R4O2 + MCO3 --> 0.05 A3O2 + 0.18 B3O2 + 0.32 ACET + 0.32 ETO2 + 0.13 RCHO ... etc.               ', &
     '   ATO2 + MCO3 --> CH2O + MCO3 + MO2                                                                ', &
     '    KO2 + MCO3 --> ALD2 + MCO3 + MO2                                                                ', &
     '   RIO2 + MCO3 --> CO2 + 0.113 DIBOO + 0.14 HC5 + 0.747 CH2O + 0.294 MACR ... etc.                  ', &
     '  HC5OO + MCO3 --> 0.17 MOBA + 0.29 DHMOB + 0.216 GLYX + 0.234 GLYC + 0.234 MGLY ... etc.           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '   VRO2 + MCO3 --> 0.6 GLYC + 0.4 MGLY + 0.4 CH2O + 0.6 MCO3 + MO2 + 0.4 HO2 ... etc.               ', &
     '   MRO2 + MCO3 --> 0.143 MGLY + 0.857 HAC + 0.143 CH2O + MO2 + 0.857 CO ... etc.                    ', &
     '   B3O2 + MCO3 --> ACET + MO2 + HO2                                                                 ', &
     '   R4N1 + MCO3 --> 0.3 R4O2 + 0.57 RCHO + 0.39 CH2O + 0.75 ALD2 + MO2 + NO2 ... etc.                ', &
     '   MAN2 + MCO3 --> CO2 + 0.5 PROPNN + 0.5 MGLY + 0.5 CH2O + MO2 + 0.5 CO ... etc.                   ', &
     '   INO2 + MCO3 --> 0.7 ISN1 + 0.23 HC5 + 0.07 CH2O + 0.035 MACR + 0.035 MVK ... etc.                ', &
     '   PRN1 + MCO3 --> CH2O + ALD2 + MO2 + NO2                                                          ', &
     '   R4O2 + MCO3 --> ACTA + MEK                                                                       ', &
     '   ATO2 + MCO3 --> ACTA + MGLY                                                                      ', &
     '    KO2 + MCO3 --> ACTA + MEK                                                                       ', &
     '   RIO2 + MCO3 --> ACTA + MEK                                                                       ', &
     '  HC5OO + MCO3 --> ACTA + MEK                                                                       ', &
     '   VRO2 + MCO3 --> ACTA + MEK                                                                       ', &
     '   MRO2 + MCO3 --> ACTA + MEK                                                                       ', &
     '   R4N1 + MCO3 --> ACTA + RCHO + NO2                                                                ', &
     '   MAN2 + MCO3 --> ACTA + RCHO + NO2                                                                ', &
     '   INO2 + MCO3 --> ACTA + RCHO + NO2                                                                ', &
     '   PRN1 + MCO3 --> ACTA + RCHO + NO2                                                                ', &
     '   B3O2 + MCO3 --> ACTA + ACET                                                                      ', &
     '   ETO2 + MCO3 --> ALD2 + MO2 + HO2                                                                 ', &
     '   ETO2 + MCO3 --> ACTA + ALD2                                                                      ', &
     '   RCO3 + MCO3 --> ETO2 + MO2                                                                       ', &
     '  NMAO3 + MCO3 --> CH2O + MCO3 + MO2                                                                ', &
     '         2 NO3 --> 2 NO2 + O2                                                                       ', &
     '     MO2 + NO2 --> MPN                                                                              ', &
     '           MPN --> MO2 + NO2                                                                        ', &
     '   ISOPNB + O3 --> 0.36 CO2 + 0.21 MVKN + 0.42 PROPNN + 0.32 MACRN + 0.16 HCOOH ... etc.            ', &
     '   ISOPND + O3 --> 0.63 CO2 + 0.09 EOH + 0.26 ETHLN + 0.06 GLYX + 0.38 PROPNN ... etc.              ', &
     '      DMS + OH --> CH2O + SO2 + MO2                                                                 ', &
     '      DMS + OH --> 0.25 MSA + 0.75 SO2 + MO2                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '     DMS + NO3 --> HNO3 + CH2O + SO2 + MO2                                                          ', &
     '      SO2 + OH --> SO4 + HO2                                                                        ', &
     '       Br + O3 --> BrO + O2                                                                         ', &
     '     BrO + HO2 --> HOBr + O2                                                                        ', &
     '      HO2 + Br --> HBr + O2                                                                         ', &
     '      OH + HBr --> Br + H2O                                                                         ', &
     '         2 BrO --> 2 Br + O2                                                                        ', &
     '         2 BrO --> Br2 + O2                                                                         ', &
     '      BrO + NO --> Br + NO2                                                                         ', &
     '    BrNO3 + Br --> Br2 + NO3                                                                        ', &
     '      Br2 + OH --> HOBr + Br                                                                        ', &
     '      HOBr + O --> BrO + OH                                                                         ', &
     '       HBr + O --> OH + Br                                                                          ', &
     '      BrO + OH --> HO2 + Br                                                                         ', &
     '      NO3 + Br --> BrO + NO2                                                                        ', &
     '     CH2O + Br --> CO + HBr + HO2                                                                   ', &
     '     ALD2 + Br --> MCO3 + HBr                                                                       ', &
     '     ACET + Br --> ATO2 + HBr                                                                       ', &
     '     C2H6 + Br --> ETO2 + HBr                                                                       ', &
     '     C3H8 + Br --> A3O2 + HBr                                                                       ', &
     '      Br + NO2 --> BrNO2                                                                            ', &
     '     BrO + NO2 --> BrNO3                                                                            ', &
     '    CHBr3 + OH --> 3 Br                                                                             ', &
     '   CH2Br2 + OH --> 2 Br                                                                             ', &
     '    CH3Br + OH --> HO2 + Br + H2O                                                                   ', &
     '     H2O + O1D --> 2 OH                                                                             ', &
     '      O1D + N2 --> O + N2                                                                           ', &
     '      O1D + O2 --> O + O2                                                                           ', &
     '      O1D + H2 --> H + OH                                                                           ', &
     '     N2O + O1D --> N2 + O2                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '     N2O + O1D --> 2 NO                                                                             ', &
     '     CH4 + O1D --> MO2 + OH                                                                         ', &
     '     CH4 + O1D --> CH2O + H2                                                                        ', &
     '     CH4 + O1D --> H + CH2O + HO2                                                                   ', &
     '        O + O2 --> O3                                                                               ', &
     '        O + O3 --> 2 O2                                                                             ', &
     '       OH + H2 --> H + H2O                                                                          ', &
     '        OH + O --> H + O2                                                                           ', &
     '       HO2 + O --> OH + O2                                                                          ', &
     '      O3 + O1D --> 2 O2                                                                             ', &
     '      O3 + O1D --> 2 O + O2                                                                         ', &
     '       OCS + O --> SO2 + CO                                                                         ', &
     '      OCS + OH --> CO2 + SO2                                                                        ', &
     '       O + NO2 --> NO + O2                                                                          ', &
     '       NO3 + O --> NO2 + O2                                                                         ', &
     '        NO + O --> NO2                                                                              ', &
     '       O + NO2 --> NO3                                                                              ', &
     '      H2O2 + O --> OH + HO2                                                                         ', &
     '        H + O2 --> HO2                                                                              ', &
     '        H + O3 --> OH + O2                                                                          ', &
     '       H + HO2 --> 2 OH                                                                             ', &
     '       H + HO2 --> H2O + O                                                                          ', &
     '       H + HO2 --> H2 + O2                                                                          ', &
     '        N + O2 --> NO + O                                                                           ', &
     '        N + NO --> O + N2                                                                           ', &
     '       N + NO2 --> N2O + O                                                                          ', &
     '       BrO + O --> Br + O2                                                                          ', &
     '      CH2O + O --> CO + OH + HO2                                                                    ', &
     '     HCl + O1D --> 0.24 H + 0.67 Cl + 0.67 OH + 0.24 ClO + 0.09 O + 0.09 HCl ... etc.               ', &
     '     HBr + O1D --> 0.15 H + 0.15 BrO + 0.65 OH + 0.2 HBr + 0.65 Br + 0.2 O ... etc.                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '     Cl2 + O1D --> 0.25 Cl2 + 0.75 Cl + 0.75 ClO + 0.25 O                                           ', &
     '    CCl4 + O1D --> 0.14 CCl4 + 2.58 Cl + 0.86 ClO + 0.14 O                                          ', &
     '   CH3Br + O1D --> 0.44 BrO + MO2 + 0.56 Br                                                         ', &
     '  CH2Br2 + O1D --> 0.05 CH2Br2 + 0.95 BrO + 0.95 Br + 0.05 O                                        ', &
     '   CHBr3 + O1D --> 0.32 CHBr3 + 0.68 BrO + 1.36 Br + 0.32 O                                         ', &
     '  HCFC22 + O1D --> 0.28 HCFC22 + 0.17 Cl + 0.55 ClO + 0.28 O                                        ', &
     '   CFC11 + O1D --> 0.12 CFC11 + 1.76 Cl + 0.88 ClO + 0.12 O                                         ', &
     '   CFC12 + O1D --> 0.14 CFC12 + 1.72 Cl + 0.86 ClO + 0.14 O                                         ', &
     '   H1211 + O1D --> 0.36 H1211 + 0.31 BrO + 0.31 Cl + 0.33 ClO + 0.33 Br ... etc.                    ', &
     '   H1301 + O1D --> 0.59 H1301 + 0.41 BrO + 0.59 O                                                   ', &
     'HCFC141b + O1D --> 0.31 HCFC141b + 0.69 Cl + 0.69 ClO + 0.31 O                                      ', &
     'HCFC142b + O1D --> 0.26 HCFC142b + 0.74 ClO + 0.26 O                                                ', &
     ' HCFC123 + O1D --> 0.21 HCFC123 + 0.79 Cl + 0.79 ClO + 0.21 O                                       ', &
     '  CFC113 + O1D --> 0.25 CFC113 + 1.5 Cl + 0.75 ClO + 0.25 O                                         ', &
     '  CFC114 + O1D --> 0.25 CFC114 + 0.75 Cl + 0.75 ClO + 0.25 O                                        ', &
     '  CFC115 + O1D --> 0.7 CFC115 + 0.3 ClO + 0.7 O                                                     ', &
     '   H2402 + O1D --> 0.25 H2402 + 0.75 BrO + 0.75 Br + 0.25 O                                         ', &
     '      Cl2 + OH --> HOCl + Cl                                                                        ', &
     '     MO2 + ClO --> ClOO + CH2O + HO2                                                                ', &
     '      OH + ClO --> Cl + HO2                                                                         ', &
     '      OH + ClO --> HCl + O2                                                                         ', &
     '     OClO + OH --> HOCl + O2                                                                        ', &
     '    Cl2O2 + OH --> ClOO + HOCl                                                                      ', &
     '      OH + HCl --> Cl + H2O                                                                         ', &
     '     HOCl + OH --> ClO + H2O                                                                        ', &
     '    ClNO2 + OH --> HOCl + NO2                                                                       ', &
     '    ClNO3 + OH --> HOCl + NO3                                                                       ', &
     '    CH3Cl + OH --> Cl + HO2 + H2O                                                                   ', &
     '   CH2Cl2 + OH --> 2 Cl + HO2                                                                       ', &
     '    CHCl3 + OH --> 3 Cl + HO2                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_11 = (/ &
     '  CH3CCl3 + OH --> 3 Cl + H2O                                                                       ', &
     '   HCFC22 + OH --> Cl + H2O                                                                         ', &
     ' HCFC141b + OH --> 2 Cl + H2O                                                                       ', &
     ' HCFC142b + OH --> Cl + H2O                                                                         ', &
     '  HCFC123 + OH --> 2 Cl + H2O                                                                       ', &
     '      CH4 + Cl --> MO2 + HCl                                                                        ', &
     '     CH2O + Cl --> CO + HO2 + HCl                                                                   ', &
     '       Cl + O3 --> ClO + O2                                                                         ', &
     '       Cl + H2 --> H + HCl                                                                          ', &
     '     H2O2 + Cl --> HO2 + HCl                                                                        ', &
     '      Cl + HO2 --> HCl + O2                                                                         ', &
     '      Cl + HO2 --> OH + ClO                                                                         ', &
     '       ClO + O --> Cl + O2                                                                          ', &
     '     HO2 + ClO --> HOCl + O2                                                                        ', &
     '      NO + ClO --> Cl + NO2                                                                         ', &
     '     ClO + NO2 --> ClNO3                                                                            ', &
     '         2 ClO --> Cl2 + O2                                                                         ', &
     '         2 ClO --> ClOO + Cl                                                                        ', &
     '         2 ClO --> OClO + Cl                                                                        ', &
     '       Cl + O2 --> ClOO                                                                             ', &
     '          ClOO --> Cl + O2                                                                          ', &
     '         2 ClO --> Cl2O2                                                                            ', &
     '         Cl2O2 --> 2 ClO                                                                            ', &
     '     ClOO + Cl --> Cl2 + O2                                                                         ', &
     '     ClOO + Cl --> 2 ClO                                                                            ', &
     '     BrO + ClO --> OClO + Br                                                                        ', &
     '     BrO + ClO --> ClOO + Br                                                                        ', &
     '     BrO + ClO --> BrCl + O2                                                                        ', &
     '     ClNO3 + O --> NO3 + ClO                                                                        ', &
     '    ClNO3 + Cl --> Cl2 + NO3                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_12 = (/ &
     '    CH3Cl + Cl --> CO + HO2 + 2 HCl                                                                 ', &
     '   CH2Cl2 + Cl --> CO + 2 Cl + HO2 + HCl                                                            ', &
     '    CHCl3 + Cl --> CO + 3 Cl + HO2 + HCl                                                            ', &
     '    HCOOH + Cl --> CO2 + H2O + HCl                                                                  ', &
     '      MO2 + Cl --> CH2O + HO2 + ClO                                                                 ', &
     '       MP + Cl --> MO2 + HCl                                                                        ', &
     '     C2H6 + Cl --> ETO2 + HCl                                                                       ', &
     '     ETO2 + Cl --> ALD2 + HO2 + ClO                                                                 ', &
     '      Cl + MOH --> CH2O + HO2 + HCl                                                                 ', &
     '      EOH + Cl --> ALD2 + HCl                                                                       ', &
     '     ACTA + Cl --> CO2 + MO2 + HCl                                                                  ', &
     '     C3H8 + Cl --> B3O2 + HCl                                                                       ', &
     '     C3H8 + Cl --> A3O2 + HCl                                                                       ', &
     '     ACET + Cl --> ATO2 + HCl                                                                       ', &
     '     ISOP + Cl --> RIO2 + HCl                                                                       ', &
     '     ALK4 + Cl --> R4O2 + HCl                                                                       ', &
     '     PRPE + Cl --> PO2 + HCl                                                                        ', &
     '     PRPE + Br --> PO2 + HBr                                                                        ', &
     '        I + NO --> INO                                                                              ', &
     '         2 INO --> I2 + 2 NO                                                                        ', &
     '       I + NO2 --> IONO                                                                             ', &
     '          IONO --> I + NO2                                                                          ', &
     '        2 IONO --> I2 + 2 NO2                                                                       ', &
     '      I2 + NO3 --> IONO2 + I                                                                        ', &
     '      IO + NO2 --> IONO2                                                                            ', &
     '         IONO2 --> IO + NO2                                                                         ', &
     '     IONO2 + I --> I2 + NO3                                                                         ', &
     '       I + BrO --> IO + Br                                                                          ', &
     '      IO + BrO --> I + Br + O2                                                                      ', &
     '      IO + BrO --> OIO + Br                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_13 = (/ &
     '      OIO + IO --> I2O3                                                                             ', &
     '         2 OIO --> I2O4                                                                             ', &
     '          I2O4 --> 2 OIO                                                                            ', &
     '      OIO + NO --> IO + NO2                                                                         ', &
     '      IO + ClO --> OClO + I                                                                         ', &
     '      IO + ClO --> I + Cl + O2                                                                      ', &
     '      IO + ClO --> ICl + O2                                                                         ', &
     '        I + O3 --> IO + O2                                                                          ', &
     '       I + HO2 --> HI + O2                                                                          ', &
     '       I2 + OH --> HOI + I                                                                          ', &
     '       HI + OH --> I + H2O                                                                          ', &
     '      HOI + OH --> IO + H2O                                                                         ', &
     '      IO + HO2 --> HOI + O2                                                                         ', &
     '       IO + NO --> I + NO2                                                                          ', &
     '          2 IO --> OIO + I                                                                          ', &
     '          2 IO --> I2O2                                                                             ', &
     '          I2O2 --> 2 IO                                                                             ', &
     '          I2O2 --> OIO + I                                                                          ', &
     '     CH3I + OH --> I + MO2 + H2O                                                                    ', &
     '      HC5 + OH --> HC5OO                                                                            ', &
     '    HC5OO + NO --> 0.17 MOBA + 0.29 DHMOB + 0.216 GLYX + 0.234 GLYC + 0.234 MGLY ... etc.           ', &
     '    HC5OO + NO --> HNO3                                                                             ', &
     '   HC5OO + HO2 --> 0.1 IAP + 0.9 GLYC + 0.9 MGLY + 0.9 OH + 0.9 HO2                                 ', &
     '   ISOPND + OH --> 0.1 IEPOXD + 0.9 ISOPNDO2 + 0.1 NO2                                              ', &
     '   ISOPNB + OH --> 0.067 IEPOXA + 0.033 IEPOXB + 0.9 ISOPNBO2 + 0.1 NO2 ... etc.                    ', &
     ' ISOPNDO2 + NO --> 0.27 DHDN + 0.21 ETHLN + 0.075 MVKN + 0.3 PROPNN + 0.057 ISOPNDO2 ... etc.       ', &
     'ISOPNDO2 + HO2 --> 0.5 ISNP + 0.2 ETHLN + 0.06 MVKN + 0.23 PROPNN + 0.01 MACRN ... etc.             ', &
     ' ISOPNBO2 + NO --> 0.21 DHDN + 0.26 MVKN + 0.44 MACRN + 0.09 GLYC + 0.09 HAC ... etc.               ', &
     'ISOPNBO2 + HO2 --> 0.51 ISNP + 0.16 MVKN + 0.28 MACRN + 0.06 GLYC + 0.06 HAC ... etc.               ', &
     '     ISNP + OH --> 0.193 ISOPNDO2 + 0.612 R4N1 + 0.193 ISOPNBO2 + 0.612 OH ... etc.                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_14 = (/ &
     '     MVKN + OH --> 0.35 PYAC + 0.65 HCOOH + 0.65 MGLY + 0.35 CH2O + NO3 ... etc.                    ', &
     '    MACRN + OH --> MACRNO2                                                                          ', &
     '  MACRNO2 + NO --> 0.93 CO2 + 0.07 HCOOH + 0.08 ACTA + 0.07 MGLY + 0.85 HAC ... etc.                ', &
     ' MACRNO2 + HO2 --> 0.93 CO2 + 0.07 HCOOH + 0.08 ACTA + 0.07 MGLY + 0.85 HAC ... etc.                ', &
     ' MACRNO2 + NO2 --> PMNN                                                                             ', &
     '          PMNN --> MACRNO2 + NO2                                                                    ', &
     '    DHMOB + OH --> 0.5 HAC + 0.5 MEK + 1.5 CO + HO2                                                 ', &
     '    DIBOO + NO --> 0.48 GLYX + 0.52 GLYC + 0.52 MGLY + 0.48 HAC + HO2 + NO2 ... etc.                ', &
     '    DIBOO + NO --> HNO3                                                                             ', &
     '   DIBOO + HO2 --> 0.85 R4P + 0.072 GLYX + 0.078 GLYC + 0.078 MGLY + 0.072 HAC ... etc.             ', &
     '     MOBA + OH --> MOBAOO                                                                           ', &
     '   MOBAOO + NO --> CO2 + RCHO + HO2 + NO2                                                           ', &
     '   MOBAOO + NO --> HNO3                                                                             ', &
     '  MOBAOO + HO2 --> 0.5 CO2 + 0.5 R4P + 0.5 RCHO + 0.5 OH + 0.5 HO2                                  ', &
     '     MOBA + O3 --> CO2 + MEK + OH + HO2                                                             ', &
     '    ETHLN + OH --> CO2 + CH2O + NO2                                                                 ', &
     '   PROPNN + OH --> MGLY + NO2                                                                       ', &
     '    CH2OO + NO --> CH2O + NO2                                                                       ', &
     '   CH2OO + NO2 --> CH2O + NO3                                                                       ', &
     '   CH2OO + SO2 --> SO4 + CH2O                                                                       ', &
     '   CH2OO + H2O --> H2O2 + CH2O                                                                      ', &
     '   CH2OO + H2O --> HCOOH                                                                            ', &
     '   MACROO + CO --> MACR                                                                             ', &
     '   MACROO + NO --> MACR + NO2                                                                       ', &
     '  MACROO + NO2 --> MACR + NO3                                                                       ', &
     '  MACROO + SO2 --> SO4 + MACR                                                                       ', &
     '  MACROO + H2O --> MRP                                                                              ', &
     '  MACROO + H2O --> H2O2 + MACR                                                                      ', &
     '    MVKOO + CO --> MVK                                                                              ', &
     '    MVKOO + NO --> MVK + NO2                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_15 = (/ &
     '   MVKOO + NO2 --> MVK + NO3                                                                        ', &
     '   MVKOO + SO2 --> SO4 + MVK                                                                        ', &
     '   MVKOO + H2O --> H2O2 + MVK                                                                       ', &
     '   MGLYOO + CO --> MGLY                                                                             ', &
     '   MGLYOO + NO --> MGLY + NO2                                                                       ', &
     '  MGLYOO + NO2 --> MGLY + NO3                                                                       ', &
     '  MGLYOO + SO2 --> SO4 + MGLY                                                                       ', &
     '  MGLYOO + H2O --> H2O2 + MGLY                                                                      ', &
     '    MGLOO + CO --> MGLY                                                                             ', &
     '    MGLOO + NO --> MGLY + NO2                                                                       ', &
     '   MGLOO + NO2 --> MGLY + NO3                                                                       ', &
     '   MGLOO + SO2 --> SO4 + MGLY                                                                       ', &
     '   MGLOO + H2O --> MCO3 + MO2                                                                       ', &
     '   MGLOO + H2O --> H2O2 + MGLY                                                                      ', &
     '  CH3CHOO + CO --> ALD2                                                                             ', &
     '  CH3CHOO + NO --> ALD2 + NO2                                                                       ', &
     ' CH3CHOO + NO2 --> ALD2 + NO3                                                                       ', &
     ' CH3CHOO + SO2 --> SO4 + ALD2                                                                       ', &
     ' CH3CHOO + H2O --> H2O2 + ALD2                                                                      ', &
     ' CH3CHOO + H2O --> ACTA                                                                             ', &
     '     GAOO + CO --> GLYC                                                                             ', &
     '     GAOO + NO --> GLYC + NO2                                                                       ', &
     '    GAOO + NO2 --> GLYC + NO3                                                                       ', &
     '    GAOO + SO2 --> SO4 + GLYC                                                                       ', &
     '    GAOO + H2O --> H2O2 + GLYC                                                                      ', &
     '    GAOO + H2O --> HAC                                                                              ', &
     '     BENZ + OH --> BRO2 + 0.252 GLYX + 1.92 CH2O + OH                                               ', &
     '     TOLU + OH --> TRO2 + 0.26 GLYX + 0.215 MGLY + 1.92 CH2O + OH                                   ', &
     '     XYLE + OH --> XRO2 + 0.268 GLYX + 0.463 MGLY + 1.92 CH2O + OH                                  ', &
     '    XYLE + NO3 --> CO2                                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_16 = (/ &
     '          MONX --> 3 CH2O                                                                           ', &
     '    BRO2 + HO2 --> LBRO2H                                                                           ', &
     '     BRO2 + NO --> LBRO2N                                                                           ', &
     '    TRO2 + HO2 --> LTRO2H                                                                           ', &
     '     TRO2 + NO --> LTRO2N                                                                           ', &
     '    XRO2 + HO2 --> LXRO2H                                                                           ', &
     '     XRO2 + NO --> LXRO2N                                                                           ', &
     '     MTPA + OH --> PIO2                                                                             ', &
     '     PIO2 + NO --> 0.12 MONITS + 0.06 MONITU + 0.07 HCOOH + 0.11 ACET + 0.43 RCHO ... etc.          ', &
     '    PIO2 + HO2 --> PIP                                                                              ', &
     '    PIO2 + MO2 --> 0.25 ROH + 0.75 RCHO + 0.75 MEK + 0.75 CH2O + HO2 + 0.25 MOH ... etc.            ', &
     '   PIO2 + MCO3 --> RCHO + MEK + 0.5 MO2 + 0.5 HO2 + RCOOH                                           ', &
     '    PIO2 + NO3 --> RCHO + MEK + HO2 + NO2                                                           ', &
     '     MTPA + O3 --> 0.02 H2O2 + 0.62 KO2 + 0.65 RCHO + 0.53 MEK + 0.14 CO ... etc.                   ', &
     '    MTPA + NO3 --> 0.1 OLNN + 0.9 OLND                                                              ', &
     '     LIMO + OH --> LIMO2                                                                            ', &
     '     LIMO + O3 --> 0.02 H2O2 + 0.01 HCOOH + 0.42 KO2 + 0.16 ETO2 + 0.46 PRPE ... etc.               ', &
     '    LIMO + NO3 --> 0.5 OLNN + 0.5 OLND                                                              ', &
     '    LIMO2 + NO --> 0.22 MONITU + 0.058 HAC + 0.289 PRPE + 0.491 RCHO + 0.289 MEK ... etc.           ', &
     '   LIMO2 + HO2 --> PIP                                                                              ', &
     '   LIMO2 + MO2 --> 0.25 ROH + 0.192 PRPE + 1.04 CH2O + 0.308 MACR + HO2 ... etc.                    ', &
     '  LIMO2 + MCO3 --> 0.192 PRPE + 0.385 CH2O + 0.308 MACR + 0.5 MO2 + 0.5 HO2 ... etc.                ', &
     '   LIMO2 + NO3 --> 0.385 PRPE + 0.385 CH2O + 0.615 MACR + HO2 + NO2                                 ', &
     '      PIP + OH --> 0.44 R4O2 + 0.08 RCHO + 0.41 MEK + 0.49 OH                                       ', &
     '     OLNN + NO --> MONITS + HO2 + NO2                                                               ', &
     '     OLND + NO --> 1.24 RCHO + 0.464 MEK + 0.287 CH2O + 2 NO2                                       ', &
     '    OLNN + HO2 --> 0.7 MONITS + 0.3 MONITU                                                          ', &
     '    OLND + HO2 --> 0.7 MONITS + 0.3 MONITU                                                          ', &
     '    OLNN + MO2 --> 0.7 MONITS + 0.3 MONITU + CH2O + 2 HO2                                           ', &
     '    OLND + MO2 --> 0.25 ROH + 0.35 MONITS + 0.15 MONITU + 0.93 RCHO + 0.348 MEK ... etc.            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_17 = (/ &
     '   OLNN + MCO3 --> 0.7 MONITS + 0.3 MONITU + MO2 + HO2                                              ', &
     '   OLND + MCO3 --> 1.24 RCHO + 0.464 MEK + 0.287 CH2O + 0.5 MO2 + NO2 + 0.5 RCOOH ... etc.          ', &
     '    OLNN + NO3 --> 0.7 MONITS + 0.3 MONITU + HO2 + NO2                                              ', &
     '    OLND + NO3 --> 1.24 RCHO + 0.464 MEK + 0.287 CH2O + 2 NO2                                       ', &
     '        2 OLNN --> 1.4 MONITS + 0.6 MONITU + HO2                                                    ', &
     '   OLNN + OLND --> 1.05 MONITS + 0.45 MONITU + 0.64 RCHO + 0.149 MEK + 0.202 CH2O ... etc.          ', &
     '        2 OLND --> 0.7 MONITS + 0.3 MONITU + 1.21 RCHO + 0.285 MEK + 0.504 CH2O ... etc.            ', &
     '   MONITS + OH --> HONIT                                                                            ', &
     '   MONITU + OH --> HONIT                                                                            ', &
     '   MONITU + O3 --> HONIT                                                                            ', &
     '  MONITU + NO3 --> HONIT                                                                            ', &
     '  MONITS + NO3 --> HONIT                                                                            ', &
     '    HONIT + OH --> HAC + NO3                                                                        ', &
     '    HC187 + OH --> 0.5 MGLY + CH2O + 0.5 MCO3 + 0.5 CO + 0.5 HO2                                    ', &
     '    HPALD + OH --> 0.085 CO2 + 0.365 HPC52O2 + 0.085 GLYX + 0.55 MGLY + 0.55 CH2O ... etc.          ', &
     '  DHPCARP + NO --> GLYX + MGLY + OH + NO2                                                           ', &
     '  HPC52O2 + NO --> GLYX + MGLY + OH + NO2                                                           ', &
     ' DHPCARP + HO2 --> RCOOH                                                                            ', &
     ' HPC52O2 + HO2 --> RCOOH                                                                            ', &
     '       DHPCARP --> CO + OH + RCOOH                                                                  ', &
     '       DHPCARP --> DHDC                                                                             ', &
     '           HO2 --> O2                                                                               ', &
     '           NO2 --> 0.5 HNO2 + 0.5 HNO3                                                              ', &
     '           NO3 --> HNO3                                                                             ', &
     '          N2O5 --> 2 HNO3                                                                           ', &
     '    N2O5 + HCl --> ClNO2 + HNO3                                                                     ', &
     '          N2O5 --> ClNO2 + HNO3                                                                     ', &
     '   BrNO3 + H2O --> HOBr + HNO3                                                                      ', &
     '   BrNO3 + HCl --> BrCl + HNO3                                                                      ', &
     '   ClNO3 + H2O --> HNO3 + HOCl                                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_18 = (/ &
     '   ClNO3 + HCl --> Cl2 + HNO3                                                                       ', &
     '   ClNO3 + HBr --> BrCl + HNO3                                                                      ', &
     'BrSALA + ClNO3 --> BrCl + HNO3                                                                      ', &
     'BrSALC + ClNO3 --> BrCl + HNO3                                                                      ', &
     '    HOCl + HCl --> Cl2 + H2O                                                                        ', &
     '    HOCl + HBr --> BrCl + H2O                                                                       ', &
     '    HOBr + HBr --> Br2 + H2O                                                                        ', &
     '    HOBr + HCl --> BrCl + H2O                                                                       ', &
     '          HOBr --> BrCl + H2O                                                                       ', &
     ' BrSALA + HOBr --> Br2                                                                              ', &
     ' BrSALC + HOBr --> Br2                                                                              ', &
     '          HOBr --> SO4H1 + HBr                                                                      ', &
     '          HOBr --> SO4H2 + HBr                                                                      ', &
     '           HCl --> O2                                                                               ', &
     '           HCl --> O2                                                                               ', &
     '      HBr + O3 --> HOBr                                                                             ', &
     '   BrSALA + O3 --> HOBr                                                                             ', &
     '   BrSALC + O3 --> HOBr                                                                             ', &
     '           HBr --> BrSALA                                                                           ', &
     '           HBr --> BrSALC                                                                           ', &
     '            HI --> AERI                                                                             ', &
     '            HI --> ISALA                                                                            ', &
     '            HI --> ISALC                                                                            ', &
     '           HOI --> ISALA                                                                            ', &
     '           HOI --> ISALC                                                                            ', &
     '          I2O2 --> 2 AERI                                                                           ', &
     '          I2O2 --> 2 ISALA                                                                          ', &
     '          I2O2 --> 2 ISALC                                                                          ', &
     '          I2O3 --> 2 AERI                                                                           ', &
     '          I2O3 --> 2 ISALA                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_19 = (/ &
     '          I2O3 --> 2 ISALC                                                                          ', &
     '          I2O4 --> 2 AERI                                                                           ', &
     '          I2O4 --> 2 ISALA                                                                          ', &
     '          I2O4 --> 2 ISALC                                                                          ', &
     '          IONO --> ISALA                                                                            ', &
     '          IONO --> ISALC                                                                            ', &
     '         IONO2 --> ISALA                                                                            ', &
     '         IONO2 --> ISALC                                                                            ', &
     '          IONO --> 0.15 IBr + 0.85 ICl + HNO2                                                       ', &
     '         IONO2 --> 0.15 IBr + 0.85 ICl + HNO3                                                       ', &
     '           HOI --> 0.15 IBr + 0.85 ICl                                                              ', &
     '          GLYX --> SOAGX                                                                            ', &
     '          MGLY --> SOAMG                                                                            ', &
     '        IEPOXA --> SOAIE                                                                            ', &
     '        IEPOXB --> SOAIE                                                                            ', &
     '        IEPOXD --> SOAIE                                                                            ', &
     '          IMAE --> SOAME                                                                            ', &
     '          LVOC --> LVOCOA                                                                           ', &
     '        ISN1OG --> ISN1OA                                                                           ', &
     '        ISOPND --> IONITA                                                                           ', &
     '        ISOPNB --> IONITA                                                                           ', &
     '         MACRN --> IONITA                                                                           ', &
     '          MVKN --> IONITA                                                                           ', &
     '          R4N2 --> IONITA                                                                           ', &
     '          DHDN --> IONITA                                                                           ', &
     '        MONITS --> MONITA                                                                           ', &
     '        MONITU --> MONITA                                                                           ', &
     '         HONIT --> MONITA                                                                           ', &
     '        IONITA --> INDIOL + HNO3                                                                    ', &
     '        MONITA --> INDIOL + HNO3                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_20 = (/ &
     '            O3 --> O + O2                                                                           ', &
     '            O3 --> O1D + O2                                                                         ', &
     '            O2 --> 2 O                                                                              ', &
     '           NO2 --> NO + O                                                                           ', &
     '          H2O2 --> 2 OH                                                                             ', &
     '            MP --> CH2O + OH + HO2                                                                  ', &
     '          CH2O --> H + CO + HO2                                                                     ', &
     '          CH2O --> CO + H2                                                                          ', &
     '          HNO3 --> OH + NO2                                                                         ', &
     '          HNO2 --> OH + NO                                                                          ', &
     '          HNO4 --> OH + NO3                                                                         ', &
     '          HNO4 --> HO2 + NO2                                                                        ', &
     '           NO3 --> O + NO2                                                                          ', &
     '           NO3 --> NO + O2                                                                          ', &
     '          N2O5 --> NO3 + NO2                                                                        ', &
     '          ALD2 --> 0.12 MCO3 + 0.88 MO2 + 0.88 CO + HO2                                             ', &
     '          ALD2 --> CH4 + CO                                                                         ', &
     '           PAN --> 0.7 MCO3 + 0.3 MO2 + 0.3 NO3 + 0.7 NO2                                           ', &
     '          RCHO --> ETO2 + CO + HO2                                                                  ', &
     '          ACET --> MCO3 + MO2                                                                       ', &
     '          ACET --> 2 MO2 + CO                                                                       ', &
     '           MEK --> 0.15 RCO3 + 0.85 ETO2 + 0.85 MCO3 + 0.15 MO2                                     ', &
     '          GLYC --> 0.9 CH2O + CO + 0.07 OH + 1.73 HO2 + 0.1 MOH                                     ', &
     '          GLYX --> 2 CO + 2 HO2                                                                     ', &
     '          GLYX --> 2 CO + H2                                                                        ', &
     '          GLYX --> CH2O + CO                                                                        ', &
     '          MGLY --> MCO3 + CO + HO2                                                                  ', &
     '           MVK --> PRPE + CO                                                                        ', &
     '           MVK --> CH2O + MCO3 + CO + HO2                                                           ', &
     '           MVK --> RCO3 + MO2                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_21 = (/ &
     '          MACR --> CH2O + MCO3 + CO + HO2                                                           ', &
     '           HAC --> CH2O + MCO3 + HO2                                                                ', &
     '          INPN --> RCHO + OH + HO2 + NO2                                                            ', &
     '          PRPN --> RCHO + OH + HO2 + NO2                                                            ', &
     '           ETP --> ALD2 + OH + HO2                                                                  ', &
     '          RA3P --> RCHO + OH + HO2                                                                  ', &
     '          RB3P --> ACET + OH + HO2                                                                  ', &
     '           R4P --> RCHO + OH + HO2                                                                  ', &
     '            PP --> CH2O + ALD2 + OH + HO2                                                           ', &
     '            RP --> ALD2 + OH + HO2                                                                  ', &
     '          RIPA --> 0.005 LVOC + 0.275 HC5 + 0.71 CH2O + 0.285 MACR + 0.425 MVK ... etc.             ', &
     '          RIPB --> 0.005 LVOC + 0.275 HC5 + 0.71 CH2O + 0.285 MACR + 0.425 MVK ... etc.             ', &
     '          RIPD --> 0.005 LVOC + 0.275 HC5 + 0.71 CH2O + 0.285 MACR + 0.425 MVK ... etc.             ', &
     '           IAP --> 0.26 GLYC + 0.58 MGLY + 0.36 HAC + 0.67 CO + OH + HO2 ... etc.                   ', &
     '          ISNP --> RCHO + OH + HO2 + NO2                                                            ', &
     '           VRP --> 0.7 GLYC + 0.3 MGLY + 0.3 CH2O + 0.7 MCO3 + OH + 0.3 HO2 ... etc.                ', &
     '           MRP --> HAC + 0.5 CH2O + 0.5 CO + OH + HO2                                               ', &
     '          MAOP --> CH2O + MCO3 + OH                                                                 ', &
     '          R4N2 --> 0.05 A3O2 + 0.18 B3O2 + 0.32 ACET + 0.32 ETO2 + 0.13 RCHO ... etc.               ', &
     '           MAP --> MO2 + OH                                                                         ', &
     '         MACRN --> MGLY + HAC + 0.5 CH2O + 0.5 CO + HO2 + NO2                                       ', &
     '          MVKN --> GLYC + MCO3 + NO2                                                                ', &
     '        ISOPNB --> HC5 + HO2 + NO2                                                                  ', &
     '           Br2 --> 2 Br                                                                             ', &
     '           BrO --> Br + O                                                                           ', &
     '          HOBr --> OH + Br                                                                          ', &
     '         BrNO3 --> NO3 + Br                                                                         ', &
     '         BrNO3 --> BrO + NO2                                                                        ', &
     '         BrNO2 --> Br + NO2                                                                         ', &
     '         CHBr3 --> 3 Br                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_22 = (/ &
     '        CH2Br2 --> 2 Br                                                                             ', &
     '         CH3Br --> MO2 + Br                                                                         ', &
     '         CH3Cl --> MO2 + Cl                                                                         ', &
     '        CH2Cl2 --> 2 Cl                                                                             ', &
     '          BrCl --> Cl + Br                                                                          ', &
     '           Cl2 --> 2 Cl                                                                             ', &
     '           ClO --> Cl + O                                                                           ', &
     '          OClO --> ClO + O                                                                          ', &
     '         Cl2O2 --> ClOO + Cl                                                                        ', &
     '         ClNO2 --> Cl + NO2                                                                         ', &
     '         ClNO3 --> Cl + NO3                                                                         ', &
     '         ClNO3 --> ClO + NO2                                                                        ', &
     '          HOCl --> Cl + OH                                                                          ', &
     '       CH3CCl3 --> 3 Cl                                                                             ', &
     '          CCl4 --> 4 Cl                                                                             ', &
     '         CFC11 --> 3 Cl                                                                             ', &
     '         CFC12 --> 2 Cl                                                                             ', &
     '        CFC113 --> 3 Cl                                                                             ', &
     '        CFC114 --> 2 Cl                                                                             ', &
     '        CFC115 --> Cl                                                                               ', &
     '       HCFC123 --> 2 Cl                                                                             ', &
     '      HCFC141b --> 2 Cl                                                                             ', &
     '      HCFC142b --> 2 Cl                                                                             ', &
     '        HCFC22 --> 2 Cl                                                                             ', &
     '         H1301 --> Br                                                                               ', &
     '         H1211 --> Cl + Br                                                                          ', &
     '         H2402 --> 2 Br                                                                             ', &
     '          ClOO --> Cl + O2                                                                          ', &
     '            I2 --> 2 I                                                                              ', &
     '           HOI --> I + OH                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_23 = (/ &
     '            IO --> I + O                                                                            ', &
     '           OIO --> I + O2                                                                           ', &
     '           INO --> I + NO                                                                           ', &
     '          IONO --> I + NO2                                                                          ', &
     '         IONO2 --> I + NO3                                                                          ', &
     '          I2O2 --> OIO + I                                                                          ', &
     '          CH3I --> I                                                                                ', &
     '         CH2I2 --> 2 I                                                                              ', &
     '        CH2ICl --> I + Cl                                                                           ', &
     '        CH2IBr --> I + Br                                                                           ', &
     '          I2O4 --> 2 OIO                                                                            ', &
     '          I2O3 --> OIO + IO                                                                         ', &
     '           IBr --> I + Br                                                                           ', &
     '           ICl --> I + Cl                                                                           ', &
     '           MPN --> CH2O + NO3 + HO2                                                                 ', &
     '           MPN --> MO2 + NO2                                                                        ', &
     '        ISOPND --> HC5 + HO2 + NO2                                                                  ', &
     '        PROPNN --> CH2O + MO2 + CO + NO2                                                            ', &
     '         ATOOH --> CH2O + MCO3 + OH                                                                 ', &
     '           N2O --> O1D + N2                                                                         ', &
     '           OCS --> SO2 + CO                                                                         ', &
     '           SO4 --> SO2 + 2 OH                                                                       ', &
     '            NO --> N + O                                                                            ', &
     '           PIP --> RCHO + OH + HO2                                                                  ', &
     '          IPMN --> 0.4 CO2 + 0.6 IMAO3 + 0.4 CH2O + 0.4 MCO3 + 0.4 NO3 ... etc.                     ', &
     '         ETHLN --> CH2O + CO + HO2 + NO2                                                            ', &
     '          DHDC --> GLYX + MGLY + 2 OH                                                               ', &
     '         HPALD --> 0.11 GLYC + 0.5 MGLY + 0.39 HAC + 0.11 MCO3 + 1.89 CO ... etc.                   ', &
     '          ISN1 --> 0.25 GLYX + 0.5 GLYC + 0.25 MGLY + 0.5 HAC + CH2O + HO2 ... etc.                 ', &
     '        MONITS --> MEK + NO2                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(2) :: EQN_NAMES_24 = (/ &
     '        MONITU --> RCHO + NO2                                                                       ', &
     '         HONIT --> HAC + NO2                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(722) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11, EQN_NAMES_12, EQN_NAMES_13, EQN_NAMES_14, &
    EQN_NAMES_15, EQN_NAMES_16, EQN_NAMES_17, EQN_NAMES_18, EQN_NAMES_19, &
    EQN_NAMES_20, EQN_NAMES_21, EQN_NAMES_22, EQN_NAMES_23, EQN_NAMES_24 /)

! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
