! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : strato_Rates.f90
! Time                 : Tue Feb 27 15:54:08 2018
! Working directory    : /home/zhuangjw/KPP/my_tests/strato/strato_code
! Equation file        : strato.kpp
! Output root filename : strato
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE strato_Rates

  USE strato_Parameters
  USE strato_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE strato_Parameters
      !USE strato_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


! End INLINED RCONST

! RCONST(1) = constant rate coefficient
! RCONST(2) = constant rate coefficient
! RCONST(3) = constant rate coefficient
! RCONST(4) = constant rate coefficient
! RCONST(5) = constant rate coefficient
! RCONST(6) = constant rate coefficient
! RCONST(7) = constant rate coefficient
! RCONST(8) = constant rate coefficient
! RCONST(9) = constant rate coefficient
! RCONST(10) = constant rate coefficient
! RCONST(11) = constant rate coefficient
! RCONST(12) = constant rate coefficient
! RCONST(13) = constant rate coefficient
! RCONST(14) = constant rate coefficient
! RCONST(15) = constant rate coefficient
! RCONST(16) = constant rate coefficient
! RCONST(17) = constant rate coefficient
! RCONST(18) = constant rate coefficient
! RCONST(19) = constant rate coefficient
! RCONST(20) = constant rate coefficient
! RCONST(21) = constant rate coefficient
! RCONST(22) = constant rate coefficient
! RCONST(23) = constant rate coefficient
! RCONST(24) = constant rate coefficient
! RCONST(25) = constant rate coefficient
! RCONST(26) = constant rate coefficient
! RCONST(27) = constant rate coefficient
! RCONST(28) = constant rate coefficient
! RCONST(29) = constant rate coefficient
! RCONST(30) = constant rate coefficient
! RCONST(31) = constant rate coefficient
! RCONST(32) = constant rate coefficient
! RCONST(33) = constant rate coefficient
! RCONST(34) = constant rate coefficient
! RCONST(35) = constant rate coefficient
! RCONST(36) = constant rate coefficient
! RCONST(37) = constant rate coefficient
! RCONST(38) = constant rate coefficient
! RCONST(39) = constant rate coefficient
! RCONST(40) = constant rate coefficient
! RCONST(41) = constant rate coefficient
! RCONST(42) = constant rate coefficient
! RCONST(43) = constant rate coefficient
! RCONST(44) = constant rate coefficient
! RCONST(45) = constant rate coefficient
! RCONST(46) = constant rate coefficient
! RCONST(47) = constant rate coefficient
! RCONST(48) = constant rate coefficient
! RCONST(49) = constant rate coefficient
! RCONST(50) = constant rate coefficient
! RCONST(51) = constant rate coefficient
! RCONST(52) = constant rate coefficient
! RCONST(53) = constant rate coefficient
! RCONST(54) = constant rate coefficient
! RCONST(55) = constant rate coefficient
! RCONST(56) = constant rate coefficient
! RCONST(57) = constant rate coefficient
! RCONST(58) = constant rate coefficient
! RCONST(59) = constant rate coefficient
! RCONST(60) = constant rate coefficient
! RCONST(61) = constant rate coefficient
! RCONST(62) = constant rate coefficient
! RCONST(63) = constant rate coefficient
! RCONST(64) = constant rate coefficient
! RCONST(65) = constant rate coefficient
! RCONST(66) = constant rate coefficient
! RCONST(67) = constant rate coefficient
! RCONST(68) = constant rate coefficient
! RCONST(69) = constant rate coefficient
! RCONST(70) = constant rate coefficient
! RCONST(71) = constant rate coefficient
! RCONST(72) = constant rate coefficient
! RCONST(73) = constant rate coefficient
! RCONST(74) = constant rate coefficient
! RCONST(75) = constant rate coefficient
! RCONST(76) = constant rate coefficient
! RCONST(77) = constant rate coefficient
! RCONST(78) = constant rate coefficient
! RCONST(79) = constant rate coefficient
! RCONST(80) = constant rate coefficient
! RCONST(81) = constant rate coefficient
! RCONST(82) = constant rate coefficient
! RCONST(83) = constant rate coefficient
! RCONST(84) = constant rate coefficient
  RCONST(85) = (2.643E-10*SUN*SUN*SUN)
  RCONST(86) = (6.120E-04*SUN)
  RCONST(87) = (1.070E-03*SUN*SUN)
  RCONST(88) = (1.817E-04*SUN*SUN)
  RCONST(89) = (3.537E-05*SUN)
  RCONST(90) = (1.289E-02*SUN)
  RCONST(91) = (2.359E-01*SUN)
  RCONST(92) = (2.883E-02*SUN)
  RCONST(93) = (2.594E-04*SUN*SUN)
  RCONST(94) = (5.269E-05*SUN*SUN)
  RCONST(95) = (4.557E-05*SUN*SUN)
  RCONST(96) = (9.113E-05*SUN*SUN)
  RCONST(97) = (3.692E-03*SUN)
  RCONST(98) = (1.243E-01*SUN)
  RCONST(99) = (3.421E-03*SUN)
  RCONST(100) = (4.606E-04*SUN)
  RCONST(101) = (2.254E-04*SUN*SUN)
  RCONST(102) = (2.505E-05*SUN*SUN)
  RCONST(103) = (1.867E-02*SUN)
  RCONST(104) = (5.950E-02*SUN)
  RCONST(105) = (1.284E-03*SUN)
  RCONST(106) = (2.074E-03*SUN)
  RCONST(107) = (7.553E-05*SUN)
  RCONST(108) = (8.303E-05*SUN)
  RCONST(109) = (2.285E-05*SUN)
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE strato_Global

  RCONST(85) = (2.643E-10*SUN*SUN*SUN)
  RCONST(86) = (6.120E-04*SUN)
  RCONST(87) = (1.070E-03*SUN*SUN)
  RCONST(88) = (1.817E-04*SUN*SUN)
  RCONST(89) = (3.537E-05*SUN)
  RCONST(90) = (1.289E-02*SUN)
  RCONST(91) = (2.359E-01*SUN)
  RCONST(92) = (2.883E-02*SUN)
  RCONST(93) = (2.594E-04*SUN*SUN)
  RCONST(94) = (5.269E-05*SUN*SUN)
  RCONST(95) = (4.557E-05*SUN*SUN)
  RCONST(96) = (9.113E-05*SUN*SUN)
  RCONST(97) = (3.692E-03*SUN)
  RCONST(98) = (1.243E-01*SUN)
  RCONST(99) = (3.421E-03*SUN)
  RCONST(100) = (4.606E-04*SUN)
  RCONST(101) = (2.254E-04*SUN*SUN)
  RCONST(102) = (2.505E-05*SUN*SUN)
  RCONST(103) = (1.867E-02*SUN)
  RCONST(104) = (5.950E-02*SUN)
  RCONST(105) = (1.284E-03*SUN)
  RCONST(106) = (2.074E-03*SUN)
  RCONST(107) = (7.553E-05*SUN)
  RCONST(108) = (8.303E-05*SUN)
  RCONST(109) = (2.285E-05*SUN)
      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE strato_Rates

