! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : strato_Parameters.f90
! Time                 : Tue Feb 27 15:54:08 2018
! Working directory    : /home/zhuangjw/KPP/my_tests/strato/strato_code
! Equation file        : strato.kpp
! Output root filename : strato
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE strato_Parameters

  USE strato_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 40 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 34 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 34 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 6 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 109 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 35 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 246 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 280 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 35 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 110 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 174 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 40 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 1 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_CH3 = 1 
  INTEGER, PARAMETER :: ind_Cl2 = 2 
  INTEGER, PARAMETER :: ind_Cl2O2 = 3 
  INTEGER, PARAMETER :: ind_ClOO = 4 
  INTEGER, PARAMETER :: ind_OClO = 5 
  INTEGER, PARAMETER :: ind_BrCl = 6 
  INTEGER, PARAMETER :: ind_HOBr = 7 
  INTEGER, PARAMETER :: ind_BrONO2 = 8 
  INTEGER, PARAMETER :: ind_HCO = 9 
  INTEGER, PARAMETER :: ind_CH3O = 10 
  INTEGER, PARAMETER :: ind_O1D = 11 
  INTEGER, PARAMETER :: ind_N2O5 = 12 
  INTEGER, PARAMETER :: ind_HBr = 13 
  INTEGER, PARAMETER :: ind_CH3OOH = 14 
  INTEGER, PARAMETER :: ind_HNO4 = 15 
  INTEGER, PARAMETER :: ind_HCl = 16 
  INTEGER, PARAMETER :: ind_H2O2 = 17 
  INTEGER, PARAMETER :: ind_HOCl = 18 
  INTEGER, PARAMETER :: ind_HNO3 = 19 
  INTEGER, PARAMETER :: ind_H = 20 
  INTEGER, PARAMETER :: ind_CH3O2 = 21 
  INTEGER, PARAMETER :: ind_ClONO2 = 22 
  INTEGER, PARAMETER :: ind_NO3 = 23 
  INTEGER, PARAMETER :: ind_CH2O = 24 
  INTEGER, PARAMETER :: ind_Br = 25 
  INTEGER, PARAMETER :: ind_OH = 26 
  INTEGER, PARAMETER :: ind_Cl = 27 
  INTEGER, PARAMETER :: ind_ClO = 28 
  INTEGER, PARAMETER :: ind_O3 = 29 
  INTEGER, PARAMETER :: ind_NO = 30 
  INTEGER, PARAMETER :: ind_BrO = 31 
  INTEGER, PARAMETER :: ind_O = 32 
  INTEGER, PARAMETER :: ind_HO2 = 33 
  INTEGER, PARAMETER :: ind_NO2 = 34 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 35 
  INTEGER, PARAMETER :: ind_H2 = 36 
  INTEGER, PARAMETER :: ind_O2 = 37 
  INTEGER, PARAMETER :: ind_N2 = 38 
  INTEGER, PARAMETER :: ind_CH4 = 39 
  INTEGER, PARAMETER :: ind_CO = 40 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_H2 = 2 
  INTEGER, PARAMETER :: indf_O2 = 3 
  INTEGER, PARAMETER :: indf_N2 = 4 
  INTEGER, PARAMETER :: indf_CH4 = 5 
  INTEGER, PARAMETER :: indf_CO = 6 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 161 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 310 

END MODULE strato_Parameters

