C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Sparse Data Header File                                          
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : saprc_f77_Sparse.h                        
C Time                 : Wed Feb 28 15:54:19 2018                  
C Working directory    : /home/zhuangjw/KPP/my_tests/compare_languages/saprc_f77
C Equation file        : saprc_f77.kpp                             
C Output root filename : saprc_f77                                 
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




C  ----------> Sparse Jacobian Data                                

C LU_IROW - Row indexes of the LU Jacobian of variables            
      INTEGER LU_IROW(920)
      COMMON /SDATA/ LU_IROW
C LU_ICOL - Column indexes of the LU Jacobian of variables         
      INTEGER LU_ICOL(920)
      COMMON /SDATA/ LU_ICOL
C LU_CROW - Compressed row indexes of the LU Jacobian of variables 
      INTEGER LU_CROW(75)
      COMMON /SDATA/ LU_CROW
C LU_DIAG - Diagonal indexes of the LU Jacobian of variables       
      INTEGER LU_DIAG(75)
      COMMON /SDATA/ LU_DIAG


C  ----------> Sparse Hessian Data                                 

C IHESS_I - Index i of Hessian element d^2 f_i/dv_j.dv_k           
      INTEGER IHESS_I(848)
      COMMON /HESSDATA/ IHESS_I
C IHESS_J - Index j of Hessian element d^2 f_i/dv_j.dv_k           
      INTEGER IHESS_J(848)
      COMMON /HESSDATA/ IHESS_J
C IHESS_K - Index k of Hessian element d^2 f_i/dv_j.dv_k           
      INTEGER IHESS_K(848)
      COMMON /HESSDATA/ IHESS_K


C  ----------> Sparse Stoichiometric Matrix                        

C STOICM - Stoichiometric Matrix in compressed column format       
      REAL*8 STOICM(1024)
      COMMON /STOICM_VALUES/ STOICM
C IROW_STOICM - Row indices in STOICM                              
      INTEGER IROW_STOICM(1024)
      COMMON /STOICM_DATA/ IROW_STOICM
C CCOL_STOICM - Beginning of columns in STOICM                     
      INTEGER CCOL_STOICM(212)
      COMMON /STOICM_DATA/ CCOL_STOICM
C ICOL_STOICM - Column indices in STOICM                           
      INTEGER ICOL_STOICM(1024)
      COMMON /STOICM_DATA/ ICOL_STOICM


C  ----------> Sparse Data for Jacobian of Reactant Products       

C ICOL_JVRP - Column indices in JVRP                               
      INTEGER ICOL_JVRP(363)
      COMMON /JVRP/ ICOL_JVRP
C IROW_JVRP - Row indices in JVRP                                  
      INTEGER IROW_JVRP(363)
      COMMON /JVRP/ IROW_JVRP
C CROW_JVRP - Beginning of rows in JVRP                            
      INTEGER CROW_JVRP(212)
      COMMON /JVRP/ CROW_JVRP

